#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat August 17, 2019
#
# DESC: Elvi to search soundtracks of movies or tv show series music
# elvis: bsost		-- Search soundtracks of movies or tv show series music (https://bsost.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search soundtracks of movies or tv show series music (https://bsost.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://bsost.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://bsost.com/?s=${escaped_args}"
fi
