#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue May 11 2013
#
# DESC: Elvi to search Fakku
# elvis: fakku		-- Search Fakku for hentai mangas (www.fakku.net)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Fakku (www.fakku.net) for hentai mangas
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.fakku.net"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.fakku.net/search/${escaped_args}"
fi
