#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue June 27, 2017
#
# DESC: Elvi to search filemare
# elvis: filemare 	-- Search filemare for FTP files (https://filemare.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search filemare (https://filemare.com) for FTP files
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://filemare.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://filemare.com/en-us/search/${escaped_args}"
fi
