#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue Mar 01, 2016
#
# DESC: Elvi to search Internet Adult Film Database
# elvis: iafd		-- Search Internet Adult Film Database (www.iafd.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Internet Adult Film Database (www.iafd.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.iafd.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.iafd.com/results.asp?searchtype=comprehensive&searchstring=${escaped_args}"
fi
