#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sun June 11, 2017
#
# DESC: Elvi to search google images
# elvis: imagesgoogle    -- Search google for images (https://images.google.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search google (https://images.google.com) for images
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://images.google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.google.com/search?site=&tbm=isch&source=hp&biw=1280&bih=655&q=${escaped_args}"
fi
