#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sun Feb 14, 2016
#
# DESC: Elvi to search ixirc for irc xdcc files
# elvis: ixirc		-- Search ixirc for irc xdcc files (http://ixirc.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search ixirc (http://ixirc.com/) for irc xdcc files 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://ixirc.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://ixirc.com/?q=${escaped_args}"
fi
