#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Nov 17 2012
#
# DESC: Elvi to search Manned ManPage
# elvis: manned		-- Search Manned linux/bsd manpages (www.manned.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Manned ManPage (www.manned.org) for manpages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.manned.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://manned.org/browse/search?q=${escaped_args}"
fi
