#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Fri January 06, 2017
#
# DESC: Elvi to search cyberlocker files
# elvis: megafindr	-- Search Cyberlocker Files (http://megafindr.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Cyberlocker Files (http://megafindr.com/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://megafindr.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://megafindr.com/search/${escaped_args}"
fi
