#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue June 27, 2017
#
# DESC: Elvi to search metabear
# elvis: metabear 	-- Search metabear [aka metabot] for FTP files (http://metabear.ru)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search metabear (http://metabear.ru) for FTP files
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://metabear.ru"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://results.metabot.ru/?wd=2&st=${escaped_args}&ln=1"
fi
