#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat July 20, 2019
#
# DESC: Elvi to search moviefiles
# elvis: moviefiles 	-- Search moviefiles for direct movie download files (https://moviefiles.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search moviefiles (https://moviefiles.org) for direct movie download files
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://moviefiles.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://moviefiles.org/search/${escaped_args}"
fi
