#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue July 31, 2018
#
# DESC: Elvi to search mypornclub
# elvis: mypornclub   	-- Search mypornclub for torrents (myporn.club)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search mypornclub (myporn.club) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://myporn.club"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://myporn.club/search/${escaped_args}"
fi
