#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue Jan 27, 2015
#
# DESC: Elvi to search asian chinese vietnamese music
# elvis: nhacso		-- Search asian chinese vietnamese music (www.nhacso.net)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search asian chinese vietnamese music (www.nhacso.net)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://nhacso.net"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://nhacso.net/tim-kiem-tat-ca.html?keyName=${escaped_args}"
fi
