#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue Feb 03 2015
#
# DESC: Elvi to search npmjs linux packages
# elvis: npmjs		-- Search NpmJs for nodejs javascript packages (www.npmjs.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search npmjs (www.npmjs.com) for nodejs javascript packages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.npmjs.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.npmjs.com/search?q=${escaped_args}"
fi
