#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Jan 17 2013
#
# DESC: Elvi to search nzbclub
# elvis: nzbclub		-- Search NZBClub for NZB (www.nzbclub.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search NZBClub (www.nzbclub.com) for NZB
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.nzbclub.com/search.aspx?q=${escaped_args}&sp=1"
fi
