#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue May 23, 2017
#
# DESC: Elvi to search nzbfriends
# elvis: nzbfriends	-- Search nzbfriends for NZB (www.nzbfriends.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search nzbfriends (www.nzbfriends.com) for NZB
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://nzbfriends.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://nzbfriends.com/?q=${escaped_args}&init=form&type=&age=0&group=&min=100&max=&sort=relevance&limit=200"
fi
