#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Mon May 20, 2019
#
# DESC: Elvi to search locally listed items for sell or trade
# elvis: offerup         -- Search locally listed items for sell or trade (https://offerup.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search locally listed items for sell or trade (https://offerup.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://offerup.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://offerup.com/search/?radius=10&q=${escaped_args}&delivery_param=p&price_max=100"
fi
