#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Nov 17 2012
#
# DESC: Elvi to search pkgs linux packages
# elvis: pkgs		-- Search PKGS for linux packages (www.pkgs.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search pkgs (www.pkgs.org) for linux packages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.pkgs.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://pkgs.org/search/?q=${escaped_args}"
fi
