#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Oct 11, 2018
#
# DESC: Elvi to search pornleech
# elvis: pornleech    	-- Search pornleech for torrents (pornleech.is)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search pornleech (pornleech.is) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://pornleech.is"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://pornleech.is/index.php?page=torrents&search=${escaped_args}&options=0&active=0"
fi
