#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Feb 18, 2016
#
# DESC: Elvi to search cyberlocker adult streaming files
# elvis: prontvst	-- Search Cyberlocker Adult Streaming Files (http://pron.tv/stream)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Cyberlocker Adult Streaming Files (http://pron.tv/stream)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://pron.tv"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://pron.tv/stream/${escaped_args}"
fi
