#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Nov 22 2014
#
# DESC: Elvi to search pururin
# elvis: pururin		-- Search pururin for hentai mangas (www.pururin.us)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search pururin (www.pururin.us) for hentai mangas
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.pururin.us"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://pururin.us/search?q=${escaped_args}"
fi
