#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu January 26, 2017
#
# DESC: Elvi to search code
# elvis: searchcode	-- Search code (https://searchcode.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search code (https://searchcode.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://searchcode.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://searchcode.com/?q=${escaped_args}"
fi
