#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue May 23, 2017
#
# DESC: Elvi to search skytorrents
# elvis: skytorrents	-- Search skytorrents for torrents (https://skytorrents.in)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search skytorrents (https://skytorrents.in) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://skytorrents.in"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.skytorrents.in/search/all/ed/1/?l=en-us&q=${escaped_args}"
fi
