#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Jan 17 2013
#
# DESC: Elvi to search slickdeals
# elvis: slickdeals	-- Search SlickDeals for low price deals (www.slickdeals.net)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search SlickDeals (www.slickdeals.net) for low price deals
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://slickdeals.net"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://slickdeals.net/newsearch.php?forumchoice%5B%5D=9&q=${escaped_args}"
fi
