#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu August 02, 2018
#
# DESC: Elvi to use the-eye fusker image extraction tool for open directories
# elvis: theeye_fusker	-- Use the-eye fusker image extraction tool for open directories (https://fusker.the-eye.eu/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Use the-eye fusker image extraction tool for open directories (https://fusker.the-eye.eu/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://fusker.the-eye.eu"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://fusker.the-eye.eu/gallery/?url=${escaped_args}"
fi
