#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Fri Feb 12, 2016
#
# DESC: Elvi to search tldr for linux simplified man pages
# elvis: tldr		-- Search tldr for linux simplified man pages (http://tldr-pages.github.io/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search tldr (http://tldr-pages.github.io/) for linux simplified man pages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://tldr-pages.github.io/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.ostera.io/tldr.jsx/#/${escaped_args}?_k=65vjze"
fi
