#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Wed Mar 11, 2020
#
# DESC: Elvi to search torrentdownloads
# elvis: torrentdownloads-- Search torrentdownloads for torrents (torrentdownloads.me)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search torrentdownloads (torrentdownloads.me) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://torrentdownloads.me"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.torrentdownloads.me/search/?search=${escaped_args}"
fi
