#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue June 27, 2017
#
# DESC: Elvi to search torrentfunk
# elvis: torrentfunk 	-- Search torrentfunk for torrents (https://www.torrentfunk.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search torrentfunk (https://www.torrentfunk.com) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.torrentfunk.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.torrentfunk.com/all/torrents/${escaped_args}.html"
fi
