#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Aug 01, 2019
#
# DESC: Elvi to search twitch
# elvis: twitch 	        -- Search twitch for live streaming video gameplay (https://www.twitch.tv)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search twitch (https://www.twitch.tv) for live streaming video gameplay
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.twitch.tv"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.twitch.tv/search/${escaped_args}"
fi
