#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Jan 17 2013
#
# DESC: Elvi to search winehq
# elvis: winehq		-- Search WineHQ for wine software ratings (www.winehq.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search winehq (www.winehq.org) for wine software ratings
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.winehq.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.winehq.org/search?cx=partner-pub-0971840239976722:w9sqbcsxtyf&cof=FORID:10&ie=UTF-8&q=${escaped_args}&siteurl=appdb.winehq.org/"
fi
