#!/usr/bin/env sh
###             _   _     _      _
###  __ _  ___ | |_| |__ | | ___| |_ _   _
### / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
###| (_| | (_) | |_| |_) | |  __/ |_| |_| |
### \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
### |___/
###       https://www.youtube.com/user/gotbletu
###       https://lbry.tv/@gotbletu
###       https://twitter.com/gotbletu
###       https://github.com/gotbletu
###       gotbletu@gmail.com
###
### Author          : gotbletu
### Name            : rofi-surfraw-websearch
### Version         : 0.1
### Date            : 2019-05-09
### Description     : using surfraw to do web searches and opens in your default web browser
### Depends On      : rofi  surfraw  gawk  sed
### Video Demo      : https://www.youtube.com/watch?v=36QV8VE5PVY
### References      : Rofi Playlist https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m
###                 : Surfraw Playlist https://www.youtube.com/playlist?list=PLqv94xWU9zZ2e-lDbmBpdASA6A6JF4Nyz

# set your browser (uncomment if needed, some GUI do not detect browser variable)
# BROWSER=firefox

surfraw -browser=$BROWSER $(sr -elvi | awk -F'-' '{print $1}' | sed '/:/d' | awk '{$1=$1};1' | rofi -kb-row-select "Tab" -kb-row-tab "Control+space" -dmenu -mesg ">>> Tab = Autocomplete" -i -p "rofi-surfraw-websearch:")
