#!/usr/bin/env sh
###             _   _     _      _
###  __ _  ___ | |_| |__ | | ___| |_ _   _
### / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
###| (_| | (_) | |_| |_) | |  __/ |_| |_| |
### \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
### |___/
###       https://www.youtube.com/user/gotbletu
###       https://lbry.tv/@gotbletu
###       https://twitter.com/gotbletu
###       https://github.com/gotbletu
###       gotbletu@gmail.com
###
### Author          : gotbletu
### Name            : rofi-surfraw-websearch
### Version         : 0.2
### Date            : 2020-04-28
### Description     : open your saved surfraw bookmarks urls in your default web browser
### Depends On      : rofi  surfraw  gawk  sed
### Video Demo      : https://www.youtube.com/watch?v=36QV8VE5PVY
### References      : Rofi Playlist https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m
###                 : Surfraw Playlist https://www.youtube.com/playlist?list=PLqv94xWU9zZ2e-lDbmBpdASA6A6JF4Nyz

# set your browser (uncomment if needed, some GUI does not detect browser variable)
# BROWSER=firefox

# surfraw -browser=$BROWSER "$(cat ~/.config/surfraw/bookmarks | sed '/^$/d' | sed '/^#/d' | sed '/^\//d' | sort -n | rofi -dmenu -mesg ">>> Edit to add new bookmarks at ~/.config/surfraw/bookmarks" -i -p "rofi-surfraw-bookmarks:")"

surfraw -browser=$BROWSER "$(grep '^[[:alnum:]]' ~/.config/surfraw/bookmarks | sort -n | rofi -threads 0 -width 100 -dmenu -mesg ">>> Edit to add new bookmarks at ~/.config/surfraw/bookmarks" -i -p "rofi-surfraw-bookmarks > ")"
