#!/bin/bash
#             _   _     _      _
#  __ _  ___ | |_| |__ | | ___| |_ _   _
# / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
#| (_| | (_) | |_| |_) | |  __/ |_| |_| |
# \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
# |___/
#       https://www.youtube.com/user/gotbletu
#       https://twitter.com/gotbletu
#       https://plus.google.com/+gotbletu
#       https://github.com/gotbletu
#       gotbleu@gmail.com

# info: rofi-multisnippet is a script to access your custom block of text snippet and copy to clipboard.
#       You can add new snippet by creating a new file and drop it in this folder ~/.multisnippet/
# requirements: rofi
# playlist: https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m

# location of snippets
dir=~/.multisnippet

# merge filename and tags into single line
results=$(for FILE in $dir/*
do
  getname=$(basename $FILE)
  gettags=$(head -n 1 $FILE)
  echo -e "$getname \t $gettags"
done)

# copy content into clipboard without tags
filename=$(echo "$(echo "$results" | rofi -dmenu -mesg ">>> Add new multisnippet at dir ~/.multisnippet/" -i -p "multisnippet:")" | cut -d' ' -f 1)
sed 1d $dir/$filename | xclip -selection clipboard

