#!/usr/bin/env sh
###             _   _     _      _         
###  __ _  ___ | |_| |__ | | ___| |_ _   _ 
### / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
###| (_| | (_) | |_| |_) | |  __/ |_| |_| |
### \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
### |___/                                  
###       https://www.youtube.com/user/gotbletu
###       https://lbry.tv/@gotbletu
###       https://twitter.com/gotbletu
###       https://github.com/gotbletu
###       gotbletu@gmail.com
###
### Author          : gotbletu
### Name            : rofi-cmus
### Version         : 0.1
### Date            : 2020-04-28
### Description     : rofi play song in cmus
### Depends On      : rofi  cmus  findutils
### Video Demo      : https://youtu.be/dTpEuQZRRDM
### References      : Rofi Playlist https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m

# select a song using rofi
SELECTED="$(find ~/Music/* -name '*.mp3' | rofi -width 100 -dmenu -i -p "CMUS Change Song > ")"

# exit script if no song is selected (e.g hit ESC)
if [ "$SELECTED" = "" ]; then exit; fi

# clear cmus queue list, add selected song to queue, play queued song
cmus-remote -c -q && cmus-remote -q "$SELECTED" && cmus-remote -n -p
