#!/usr/bin/env sh
###             _   _     _      _
###  __ _  ___ | |_| |__ | | ___| |_ _   _
### / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
###| (_| | (_) | |_| |_) | |  __/ |_| |_| |
### \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
### |___/
###       https://www.youtube.com/user/gotbletu
###       https://lbry.tv/@gotbletu
###       https://twitter.com/gotbletu
###       https://github.com/gotbletu
###       gotbletu@gmail.com
###
### Author          : gotbletu
### Name            : rofi-snippet
### Version         : 0.1
### Date            : 2019-05-09
### Description     : access your single line custom text snippet and copy to clipboard
### Depends On      : rofi  surfraw  gawk  sed
### Video Demo      : https://www.youtube.com/watch?v=36QV8VE5PVY
### References      : Rofi Playlist https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m
### Notes           : You can add new snippet. $EDITOR ~/.snippetrc

selected="$(cat $HOME/.snippetrc | sed '/^$/d' | sort -n | rofi -width 100 -dmenu -mesg ">>> Edit to add new snippet at ~/.snippetrc" -i -p "snippet:")"

# remove tags, leading and trailing spaces, also no newline
echo "$selected" | sed -e s/\;\;\.\*\$// | sed 's/^[ \t]*//;s/[ \t]*$//' | tr -d '\n' | xclip -selection clipboard
