#!/bin/bash
#             _   _     _      _
#  __ _  ___ | |_| |__ | | ___| |_ _   _
# / _` |/ _ \| __| '_ \| |/ _ \ __| | | |
#| (_| | (_) | |_| |_) | |  __/ |_| |_| |
# \__, |\___/ \__|_.__/|_|\___|\__|\__,_|
# |___/
#       https://www.youtube.com/user/gotbletu
#       https://twitter.com/gotbletu
#       https://plus.google.com/+gotbletu
#       https://github.com/gotbletu
#       gotbleu@gmail.com

# info: a script to search chromium web browser history
# requirements: rofi chromium
# playlist: https://www.youtube.com/playlist?list=PLqv94xWU9zZ0LVP1SEFQsLEYjZC_SUB3m
# references: https://junegunn.kr/2015/04/browsing-chrome-history-with-fzf/
#             https://github.com/junegunn/fzf/wiki/examples#browsing-history

local cols sep
cols=$(( COLUMNS / 3 ))
sep='{::}'

cp -f ~/.config/chromium/Default/History /tmp/h

sqlite3 -separator $sep /tmp/h \
  "select substr(title, 1, $cols), url
   from urls order by last_visit_time desc" |
awk -F $sep '{printf "%-'$cols's  \x1b[36m%s\x1b[m\n", $1, $2}' |
sed 's#.*\(https*://\)#\1#' | rev | cut -c4- | rev |
rofi -threads 0 -width 100 -dmenu -i -p "chromium history:" | xargs xdg-open

