#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Wed Mar 12, 2020
#
# DESC: Elvi to search 0xxx
# elvis: 0xxx            -- Search 0xxx for adult porn torrents (0xxx.ws)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search 0xxx (0xxx.ws) for adult porn torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://0xxx.ws"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://0xxx.ws/index.php?s=${escaped_args}"
fi
