#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sun Feb 21, 2016
#
# DESC: Elvi to search mirrored aur package builds
# elvis: aurmirror	-- Search Mirrored AUR Package Builds (http://pkgbuild.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Mirrored AUR Package Builds (http://pkgbuild.com/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://pkgbuild.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://pkgbuild.com/git/aur-mirror.git/plain/${escaped_args}/PKGBUILD"
fi
