#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue January 10, 2017
#
# DESC: Elvi to search btdb
# elvis: btdb    	-- Search btdb for torrents (https://btdb.in)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search btdb (https://btdb.in) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://btdb.in"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://btdb.in/q/${escaped_args}/?sort=time"
fi
