#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Feb 27, 2016
#
# DESC: Elvi to search google webpage cache
# elvis: cachegoogle	-- Search google for webpage cache (https://google.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search google (https://google.com) for webpage cache
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://webcache.googleusercontent.com/search?q=cache:${escaped_args}"
fi
