#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue November 21, 2017
#
# DESC: Elvi to search asian chinese vietnamese music
# elvis: chiasenhac	-- Search asian chinese vietnamese music (http://chiasenhac.vn)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search asian chinese vietnamese music (http://chiasenhac.vn)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://chiasenhac.vn"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://search.chiasenhac.vn/search.php?s=${escaped_args}"
fi
