#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue June 27, 2017
#
# DESC: Elvi to search demonoid
# elvis: demonoid 	-- Search demonoid for torrents (https://www.demonoid.pw)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search demonoid (https://www.demonoid.pw) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.demonoid.pw"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.demonoid.pw/files/?category=0&subcategory=All&quality=All&seeded=2&external=2&query=${escaped_args}&uid=0&sort=S"
fi
