#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue May 23, 2017
#
# DESC: Elvi to search eztv
# elvis: eztv 	        -- Search eztv for torrents (https://eztv.ag)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search eztv (https://eztv.ag) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://eztv.ag"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://eztv.ag/search/${escaped_args}"
fi
