#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu February 09, 2017
#
# DESC: Elvi to search google drive
# elvis: gdrive  	-- Search google drive for personal files (https://drive.google.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search google drive for personal files (https://drive.google.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://drive.google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://drive.google.com/drive/search?q=${escaped_args}"
fi
