#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sun January 28, 2018
#
# DESC: Elvi to search Gist
# elvis: gist         	-- Search Gist for text files paste dump (https://gist.github.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Gist (www.gist.com) for text files paste dump
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://gist.github.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://gist.github.com/search?utf8=✓&q=${escaped_args}"
fi
