#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Nov 22 2014
#
# DESC: Elvi to search HentaiBedta
# elvis: hentaibedta	-- Search HentaiBedta for hentai mangas (www.hentaibedta.net)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search HentaiBedta (www.hentaibedta.net) for hentai mangas
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.hentaibedta.net"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.hentaibedta.net/?s=${escaped_args}"
fi
