#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu August 02, 2018
#
# DESC: Elvi to search internet radio stations
# elvis: internetradio   -- Search internet radio stations (https://www.internet-radio.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search internet radio stations (https://www.internet-radio.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.internet-radio.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.internet-radio.com/stations/${escaped_args}/"
fi
