#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu December 29, 2016
#
# DESC: Elvi to search katcr
# elvis: kickasstorrents -- Search kickasstorrents for torrents (katcr.co)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search kickasstorrents (katcr.co) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://katcr.co"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://katcr.co/katsearch/page/1/${escaped_args}"
fi
