#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sub Feb 09 2020
#
# DESC: Elvi to search LBRY
# elvis: lbry		-- Search LBRY for videos (www.lbry.tv)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search LBRY (www.lbry.tv) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.lbry.tv"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://lbry.tv/$/search?q=${escaped_args}"
fi
