#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue June 27, 2017
#
# DESC: Elvi to search mmnt
# elvis: mmnt 	        -- Search mmnt [aka mamont] for FTP files (http://mmnt.ru/int)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search mmnt (http://mmnt.ru) for FTP files
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://mmnt.ru/int"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.mmnt.ru/int/get?st=${escaped_args}"
fi
