#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue Nov 06 2012
#
# DESC: Elvi to search Motherless
# elvis: motherless	-- Search Motherless for adult videos (www.motherless.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Motherless (www.motherless.com) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.motherless.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://motherless.com/search/videos?q=${escaped_args}"
fi
