#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu June 06, 2013
#
# DESC: Elvi to search mymangalist
# elvis: mymangalist	-- Search myanimelist for manga information (www.myanimelist.net)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search mymangalist (www.myanimelist.net) for manga information
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.myanimelist.net"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://myanimelist.net/manga.php?q=${escaped_args}"
fi
