#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue June 11, 2019
#
# DESC: Elvi to search nyaasi
# elvis: nyaasi		-- Search nyaa for anime torrents (https://nyaa.si)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search nyaasi (https://nyaa.si) for anime torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://nyaa.si"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://nyaa.si/?f=2&c=0_0&q=${escaped_args}"
fi
