#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Mon November 20, 2017
#
# DESC: Elvi to search google for open directories from google drive files
# elvis: opendir_googledrive	-- Search google for open directories from google drive files (https://www.google.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search google for open directories from google drive files (https://www.google.com)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.google.com/search?q=site%3Adrive.google.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.google.com/search?q=site%3Adrive.google.com+${escaped_args}"
fi
