#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat Nov 17 2012
#
# DESC: Elvi to search PornMD
# elvis: pornmd		-- Search PornMD for adult videos (www.pornmd.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search PornMD (www.pornmd.com) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.pornmd.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.pornmd.com/straight/${escaped_args}"
fi
