#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Mon October 02, 2017
#
# DESC: Elvi to search PornHub
# elvis: pornhub		-- Search PornHub for adult videos (www.pornhub.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search PornHub (www.pornhub.com) for adult videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.pornhub.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.pornhub.com/video/search?search=${escaped_args}"
fi
