#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat October 26, 2013
#
# DESC: Elvi to search Python Package Index
# elvis: python		-- Search Python Package Index (https://pypi.python.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Python Package Index (https://pypi.python.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://pypi.python.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://pypi.python.org/pypi?%3Aaction=search&term=${escaped_args}"
fi
