#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Feb 18, 2016
#
# DESC: Elvi to search cyberlocker files
# elvis: rapid4me	-- Search Cyberlocker Files (http://rapid4me.com/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Cyberlocker Files (http://rapid4me.com/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://rapid4me.com/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://rapid4me.com/?q=${escaped_args}"
fi
