#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue January 17, 2017
#
# DESC: Elvi to search rubygems Package Index
# elvis: rubygems	-- Search rubygems Package Index (https://rubygems.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search rubygems Package Index (https://rubygems.org)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://rubygems.org"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://rubygems.org/search?utf8=✓&query=${escaped_args}"
fi
