#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu August 02, 2018
#
# DESC: Elvi to search the-eye for open directories files
# elvis: theeye_opendir	-- Search the-eye for open directories files (https://od-db.the-eye.eu/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search the-eye for open directories files (https://od-db.the-eye.eu/)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://od-db.the-eye.eu/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://od-db.the-eye.eu/search?q=${escaped_args}"
fi
