#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu April 05, 2018
#
# DESC: Elvi to search themirrorbay
# elvis: themirrorbay 	-- Search themirrorbay for torrents (https://thepiratebay.rocks)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search themirrorbay (https://thepiratebay.rocks) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://thepiratebay.rocks"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://thepiratebay.rocks/search/${escaped_args}"
fi
