#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Fri August 05, 2016
#
# DESC: Elvi to search torrentproject
# elvis: torrentproject	-- Search torrentproject for torrents (https://torrentproject.se)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search torrentproject (https://torrentproject.se) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://torrentproject.se"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://torrentproject.se/?safe=off&t=${escaped_args}"
fi
