#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Feb 25 2016
#
# DESC: Elvi to search tsumino
# elvis: tsumino		-- Search tsumino for hentai mangas (www.tsumino.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search tsumino (www.tsumino.com) for hentai mangas
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.tsumino.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.tsumino.com/Browse/Search?q=${escaped_args}"
fi
