#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Thu Feb 14, 2020
#
# DESC: Elvi to search cyberlocker files
# elvis: ulozto 	        -- Search Cyberlocker Files (http://ulozto.to)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search Cyberlocker Files (http://ulozto.to)
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://ulozto.to"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://ulozto.net/hledej?type=archives&q=${escaped_args}"
fi
