#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat August 17, 2019
#
# DESC: Elvi to search xdcchorriblesubs for irc xdcc anime video files
# elvis: xdcchorriblesubs   -- Search xdcchorriblesubs for irc xdcc anime video files (https://xdcc.horriblesubs.info)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search xdcchorriblesubs (https://xdcc.horriblesubs.info) for irc xdcc anime video files 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://xdcc.horriblesubs.info"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://xdcc.horriblesubs.info/?search=${escaped_args}"
fi
