#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Sat August 17, 2019
#
# DESC: Elvi to search xdccit for irc xdcc files
# elvis: xdccit		-- Search xdccit for irc xdcc files (http://xdcc.it/)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search xdccit (http://xdcc.it/) for irc xdcc files 
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://xdcc.it/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://xdcc.it/?q=${escaped_args}"
fi
