#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Tue Nov 06 2012
#
# DESC: Elvi to search YouPorn
# elvis: youporn		-- Search YouPorn for adult videos (www.youporn.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search YouPorn (www.youporn.com) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "http://www.youporn.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "http://www.youporn.com/search/?query=${escaped_args}"
fi
