#!/bin/sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
#
# DATE: Fri August 05, 2016
#
# DESC: Elvi to search zooqle
# elvis: zooqle	        -- Search zooqle for torrents (https://zooqle.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search zooqle (https://zooqle.com) for torrents
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://zooqle.com"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://zooqle.com/search?q=${escaped_args}"
fi
