#!/usr/bin/env sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
  printf "%s\n" "desc: create tar.gz archive"
  printf "%s\n" "usage: ${0##*/} [file|directory]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} file.mp3"
  printf "%s\n" "  $ ${0##*/} file1.mp3 file2.pdf dir/"
  printf "%s\n" "  $ ${0##*/} *.mp3"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  tar czf "$1".tar.gz "$@"
fi
