#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
  printf "%s\n" "desc: create cbz archive for comicbooks"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [directory]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} dir"
  printf "%s\n" "  $ ${0##*/} dir1 dir2 dir3"
  printf "%s\n" "  $ ${0##*/} */"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  myArray=("$@")
  for arg in "${myArray[@]}"; do
    zip -r "${arg%/}.cbz" "$arg"
  done
fi
