#!/usr/bin/env sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
  printf "%s\n" "desc: copy files without overwriting"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [source] [target]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} /dir1/ /dir2/"
}
if [ $# -lt 2 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  cp -n -- "$@"
fi
