#!/usr/bin/env sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
  printf "%s\n" "desc: restore file from trash-can similar to gui file manager"
  printf "\n"
  printf "%s\n" "usage: ${0##*/}"
}
if [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
elif command -v trash-restore >/dev/null; then
  trash-restore
else
  printf "%s\n" "missing trash-cli"
  exit 1
fi
