#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
  printf "%s\n" "desc: list and grep with file permission and color highlights"
  printf "%s\n" "depend: grep gawk"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [keyword]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} png"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  keyword=$(printf "%s\n" "${@/ /.*}")
  ls -hlA --color=yes \
    | awk '{k=0;for(i=0;i<=8;i++)k+=((substr($1,i+2,1)~/[rwx]/)*2^(8-i));if(k)printf(" %0o ",k);print}' \
    | grep -iE "$keyword"
fi
