#!/usr/bin/env sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

helpmsg() {
  printf "%s\n" "desc: QR code generator"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [string]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} https://www.youtube.com/user/gotbletu"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  curl http://qrenco.de/"$1"
fi
