#!/usr/bin/env sh
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)
# REFF: http://www.webupd8.org/2009/04/split-ape-and-flac-files-in-ubuntu-and.html
#       https://wiki.archlinux.org/index.php/CUE_Splitting

CUE_FILE="$1"
APE_FILE="$2"
helpmsg() {
  printf "%s\n" "desc: split ape cue files to flac audio"
  printf "%s\n" "depend: shntool cuetools mac (APE codec and decompressor)"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [cuefile] [apefile]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} madonna.cue madonna.ape"
}
if [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
elif [ $# -lt 2 ]; then
  helpmsg
  exit 1
else
  cuebreakpoints "$CUE_FILE" | shnsplit -o flac "$APE_FILE"
fi
