#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

DIR=CONVERTED_MKVHEVC
helpmsg() {
  printf "%s\n" "desc: convert to mkv video (x265 hevc)"
  printf "%s\n" "depend: ffmpeg x265"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [file]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} file.mp4"
  printf "%s\n" "  $ ${0##*/} file1.mp4 file2.mp4 file3.mp4"
  printf "%s\n" "  $ ${0##*/} *.mp4"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  mkdir -p "$DIR"
  myArray=("$@")
  for arg in "${myArray[@]}"; do
    if [[ -f "$arg" && ! -f "$DIR/${arg%.*}.mkv" ]]; then
      # x265 CRF ranges: 0 (lossless) <-- 18 <-- 23 (better) --> 28 (default) --> 51 (worst)
      # x265 CRF 28 = x264 CRF 23
      # convert audio to aac
      # ffmpeg -i "$arg" -c:v libx265 -preset medium -crf 28 -x265-params lossless -c:a aac -q:a 6 -c:s copy "${arg%.*} [x265].mkv"
      # very clear (same as OG)
      # ffmpeg -i "$arg" -c:v libx265 -preset medium -crf 23 -x265-params lossless -c:a copy -c:s copy "${arg%.*} x265 crf23.mkv"
      # smaller file size, semi clear to OG
      ffmpeg -i "$arg" -c:v libx265 -preset medium -crf 28 -x265-params lossless -c:a copy -c:s copy "$DIR/${arg%.*}.mkv"
    else
      printf "%s\n" "$arg is invalid or output file already exist"
      exit 1
    fi
  done
fi
