#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

DIR=CONVERTED_PSP
helpmsg() {
  printf "%s\n" "desc: convert to psp video (sony playstation portable)"
  printf "%s\n" "depend: ffmpeg"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [file]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} file.mp4"
  printf "%s\n" "  $ ${0##*/} file1.mp4 file2.mp4 file3.mp4"
  printf "%s\n" "  $ ${0##*/} *.mp4"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  mkdir -p "$DIR"
  myArray=("$@")
  for arg in "${myArray[@]}"; do
    if [[ -f "$arg" && ! -f "$DIR/${arg%.*}.mp4" ]]; then
      ffmpeg -i "$arg" -s 320x240 -b:v 512000 -ar 24000 -ab 64000 -f psp -r 29.97 -strict experimental "$DIR/${arg%.*}.mp4"
    else
      printf "%s\n" "$arg is invalid or output file already exist"
      exit 1
    fi
  done
fi
