#!/usr/bin/env bash
# AUTHOR: gotbletu (@gmail|twitter|youtube|github|lbry)

DIR=CONVERTED_OGV
helpmsg() {
  printf "%s\n" "desc: convert to ogv video"
  printf "%s\n" "depend: ffmpeg libtheora libvorbis"
  printf "\n"
  printf "%s\n" "usage: ${0##*/} [file]"
  printf "\n"
  printf "%s\n" "  $ ${0##*/} file.mp4"
  printf "%s\n" "  $ ${0##*/} file1.mp4 file2.mp4 file3.mp4"
  printf "%s\n" "  $ ${0##*/} *.mp4"
}
if [ $# -lt 1 ]; then
  helpmsg
  exit 1
elif [ "$1" = -h ] || [ "$1" = --help ]; then
  helpmsg
  exit 0
else
  mkdir -p "$DIR"
  myArray=("$@")
  for arg in "${myArray[@]}"; do
    if [[ -f "$arg" && ! -f "$DIR/${arg%.*}.ogv" ]]; then
      ffmpeg -i "$arg" -codec:v libtheora -qscale:v 7 -codec:a libvorbis -qscale:a 5 "$DIR/${arg%.*}.ogv"
    else
      printf "%s\n" "$arg is invalid or output file already exist"
      exit 1
    fi
  done
fi
