#!/usr/bin/env sh
USER_AGENT="Mozilla/5.0 (iPhone9,3; U; CPU iPhone OS 10_0_1 like Mac OS X) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Mobile/14A403 Safari/602.1"

if [ "$W3M_SETTING_MODE" = "xsession" ]; then
  # open settings options
  xdotool type "$W3M_HOTKEY_OPTIONS"
  # jump to user agent
  xdotool type "155$W3M_HOTKEY_LINK_BEGIN"
  # clear user agent string
  xdotool key Return
  xdotool key ctrl+u
  # new user agent string
  xdotool type "$USER_AGENT"
  xdotool key Return
  # save changes
  xdotool type "173$W3M_HOTKEY_LINK_BEGIN"
  xdotool key Return
  # refresh page
  xdotool type "$W3M_HOTKEY_RELOAD"
elif [ "$W3M_SETTING_MODE" = "tmux" ]; then
  # open settings options
  tmux send-keys "$W3M_HOTKEY_OPTIONS"
  # jump to user agent
  tmux send-keys "155$W3M_HOTKEY_LINK_BEGIN"
  # clear user agent string
  tmux send-keys 'Enter' 'C-u'
  # new user agent string
  tmux send-keys "$USER_AGENT" 'Enter'
  # save changes
  tmux send-keys "173$W3M_HOTKEY_LINK_BEGIN" 'Enter'
  # refresh page
  tmux send-keys "$W3M_HOTKEY_RELOAD"
fi
